# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: prometheusreceiver

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Remove storing pointers to pdata points, allow removing unnecessary pdata points copy.

# One or more tracking issues related to the change
issues: [13922]
